<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Summit Online School gives every learner a clear, connected path forward.">
    <title>Summit Online School | Learn with confidence</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet">
    <script>document.documentElement.classList.add('has-js');</script>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        :root { --green:#0c7261; --green-dark:#064a3f; --green-deep:#043b33; --yellow:#f8eb2f; --paper:#f8f7f1; --cream:#efeee7; --ink:#122722; --muted:#61706b; --line:#d7ded9; --white:#fff; --coral:#f0644d; --mint:#bce6d5; }
        * { box-sizing:border-box; }
        html { scroll-behavior:smooth; }
        body.landing-page { background:var(--paper); color:var(--ink); font-family:'DM Sans',Arial,sans-serif; margin:0; overflow-x:hidden; }
        .landing-page h1,.landing-page h2,.landing-page h3,.landing-page p { margin-top:0; }
        .landing-page a { color:inherit; text-decoration:none; }
        .landing-page button,.landing-page input,.landing-page textarea { font:inherit; }
        .skip-link { background:var(--yellow); color:var(--ink); font-weight:800; left:1rem; padding:.75rem 1rem; position:fixed; top:-4rem; transition:top .2s; z-index:100; }
        .skip-link:focus { top:1rem; }
        .page-width { margin:0 auto; max-width:1200px; padding-left:28px; padding-right:28px; }
        .site-header { background:rgba(248,247,241,.94); border-bottom:1px solid rgba(12,114,97,.12); position:sticky; top:0; z-index:30; backdrop-filter:blur(15px); }
        .nav-shell { align-items:center; display:flex; gap:28px; height:76px; justify-content:space-between; }
        .brand { align-items:center; display:inline-flex; font-family:'Manrope',sans-serif; font-size:1rem; font-weight:800; gap:10px; letter-spacing:-.045em; line-height:1.05; min-width:170px; }
        .brand-mark { background:#fff; border:1px solid #d7ded9; border-radius:50%; display:grid; height:48px; overflow:hidden; place-items:center; width:48px; }
        .brand-mark img { height:41px; object-fit:contain; width:41px; }
        .brand span:last-child { color:var(--green); display:block; font-size:.67rem; letter-spacing:.1em; margin-top:3px; text-transform:uppercase; }
        .nav-links { align-items:center; display:flex; gap:24px; margin-left:auto; }
        .nav-links a { color:#37524a; font-size:.78rem; font-weight:800; letter-spacing:.025em; padding:9px 0; position:relative; text-transform:uppercase; }
        .nav-links a::after { background:var(--green); bottom:3px; content:''; height:2px; left:0; position:absolute; transform:scaleX(0); transform-origin:left; transition:transform .2s; width:100%; }
        .nav-links a:hover::after,.nav-links a:focus-visible::after { transform:scaleX(1); }
        .nav-actions { align-items:center; display:flex; gap:16px; }
        .login-link { color:var(--green); font-size:.82rem; font-weight:800; }
        .pill { align-items:center; border:1px solid transparent; border-radius:999px; display:inline-flex; font-size:.78rem; font-weight:800; gap:8px; justify-content:center; letter-spacing:.015em; min-height:43px; padding:0 19px; transition:transform .18s,background .18s,box-shadow .18s; }
        .pill:hover { transform:translateY(-2px); }
        .pill-primary { background:var(--green); box-shadow:0 7px 0 rgba(4,59,51,.15); color:#fff; }
        .pill-primary:hover { background:var(--green-dark); }
        .pill-yellow { background:var(--yellow); box-shadow:0 7px 0 rgba(47,51,8,.2); color:var(--ink); }
        .pill-yellow:hover { background:#e9dc28; }
        .pill-outline { border-color:rgba(255,255,255,.6); color:#fff; }
        .pill-outline:hover { background:#fff; color:var(--green-deep); }
        .pill svg { height:15px; width:15px; }
        .nav-toggle { background:#fff; border:1px solid var(--line); border-radius:9px; color:var(--green-deep); cursor:pointer; display:none; height:40px; padding:0; width:40px; }
        .nav-toggle svg { height:21px; width:21px; }
        .hero { padding:13px 0 0; }
        .hero-frame { background:var(--green-deep); border-radius:0 0 30px 30px; color:#fff; min-height:575px; overflow:hidden; position:relative; }
        .hero-frame::before { background:linear-gradient(115deg,rgba(4,59,51,.36),transparent 58%); content:''; inset:0; position:absolute; z-index:1; }
        .hero-frame::after { border:1px solid rgba(248,235,47,.35); border-radius:50%; content:''; height:430px; position:absolute; right:-185px; top:-145px; width:430px; }
        .hero-grid { align-items:center; display:grid; grid-template-columns:.84fr 1.16fr; min-height:575px; position:relative; z-index:2; }
        .hero-copy { padding:75px 0 82px; position:relative; z-index:3; }
        .overline { align-items:center; color:var(--yellow); display:flex; font-size:.7rem; font-weight:800; gap:8px; letter-spacing:.12em; margin-bottom:17px; text-transform:uppercase; }
        .overline::before { background:var(--yellow); content:''; height:2px; width:26px; }
        .hero h1 { font-family:'Manrope',sans-serif; font-size:clamp(2.9rem,5.2vw,5.15rem); font-weight:800; letter-spacing:-.07em; line-height:.92; margin-bottom:22px; max-width:560px; text-transform:uppercase; }
        .hero h1 strong { color:var(--yellow); font:inherit; }
        .hero-copy p { color:#d0e1da; font-size:1.04rem; line-height:1.7; margin-bottom:30px; max-width:470px; }
        .hero-buttons { display:flex; flex-wrap:wrap; gap:12px; }
        .hero-note { align-items:center; color:#c3d6cf; display:flex; font-size:.76rem; font-weight:700; gap:9px; margin-top:35px; }
        .hero-note i { background:var(--yellow); border-radius:50%; color:var(--green-deep); display:grid; font-style:normal; height:24px; place-items:center; width:24px; }
        .hero-visual { align-self:stretch; min-height:510px; overflow:hidden; position:relative; }
        .hero-sun { background:var(--yellow); border-radius:50%; height:285px; opacity:.96; position:absolute; right:75px; top:88px; width:285px; }
        .hero-pattern { background-image:radial-gradient(rgba(255,255,255,.2) 1px,transparent 1px); background-size:17px 17px; height:180px; position:absolute; right:15px; top:75px; transform:rotate(12deg); width:185px; }
        .school-scene { bottom:0; height:420px; position:absolute; right:0; width:100%; }
        .school-scene .ground { background:#08342c; bottom:0; height:73px; left:0; position:absolute; right:0; }
        .school-scene .building { background:#f5edcf; bottom:56px; box-shadow:inset -16px 0 rgba(12,114,97,.16); height:252px; position:absolute; right:7%; width:54%; }
        .school-scene .building::before { background:var(--green); bottom:0; content:''; height:82px; left:40%; position:absolute; width:70px; }
        .school-scene .building::after { background:repeating-linear-gradient(90deg,#277d6f 0 24px,transparent 24px 47px); content:''; height:85px; left:31px; position:absolute; top:42px; width:72%; }
        .school-scene .roof { border-bottom:38px solid #e2be50; border-left:72px solid transparent; border-right:72px solid transparent; height:0; position:absolute; right:1%; top:75px; width:60%; }
        .school-scene .tower { background:#e9c85d; bottom:56px; height:310px; position:absolute; right:60%; width:105px; }
        .school-scene .tower::before { border-bottom:44px solid #e9c85d; border-left:53px solid transparent; border-right:53px solid transparent; content:''; position:absolute; top:-44px; }
        .school-scene .tower::after { background:repeating-linear-gradient(90deg,#277d6f 0 18px,transparent 18px 32px); content:''; height:56px; left:18px; position:absolute; top:47px; width:70px; }
        .student { bottom:53px; position:absolute; z-index:3; }
        .student .leg { background:#233d3a; bottom:0; height:90px; position:absolute; width:23px; }
        .student .leg.one { left:28px; transform:rotate(4deg); }.student .leg.two { left:56px; transform:rotate(-4deg); }
        .student .body { background:#f7f7f2; border:5px solid #0b2f2a; border-radius:34px 34px 15px 15px; bottom:75px; height:117px; position:absolute; width:93px; }
        .student .body::after { background:var(--yellow); border-radius:0 0 50% 50%; content:''; height:32px; left:13px; position:absolute; top:0; width:58px; }
        .student .head { background:#9a623e; border-radius:45% 45% 42% 42%; bottom:174px; height:73px; left:16px; position:absolute; width:61px; }
        .student .hair { background:#38251c; border-radius:45% 45% 18px 18px; bottom:219px; height:30px; left:11px; position:absolute; width:72px; z-index:1; }
        .student .bag { background:var(--green); border:4px solid #082f29; border-radius:12px 12px 18px 18px; bottom:95px; height:77px; position:absolute; right:-21px; transform:rotate(-8deg); width:44px; }
        .student-one { left:11%; transform:scale(1.06); }.student-two { left:38%; transform:scale(.85); transform-origin:bottom; }.student-three { right:8%; transform:scale(.78); transform-origin:bottom; }
        .student-two .head { background:#d49b75; }.student-two .hair { background:#211d1b; }.student-two .body { background:#cee8dd; }.student-two .bag { background:var(--yellow); }
        .student-three .head { background:#6e402b; }.student-three .hair { background:#24190f; border-radius:50% 50% 30% 30%; height:38px; }.student-three .body { background:#fff; }.student-three .bag { background:var(--coral); }
        .hero-stamp { align-items:center; background:var(--yellow); border:2px solid var(--green-deep); border-radius:50%; bottom:44px; color:var(--green-deep); display:flex; flex-direction:column; font-family:'Manrope',sans-serif; font-size:.59rem; font-weight:800; height:92px; justify-content:center; line-height:1.1; position:absolute; right:42%; text-align:center; transform:rotate(10deg); width:92px; z-index:5; }
        .hero-stamp b { display:block; font-size:1.5rem; letter-spacing:-.08em; }
        .intro { padding:105px 0 95px; }
        .split-intro { align-items:center; display:grid; gap:78px; grid-template-columns:.9fr 1fr; }
        .section-label { color:var(--green); font-size:.68rem; font-weight:800; letter-spacing:.12em; margin-bottom:12px; text-transform:uppercase; }
        .section-title { font-family:'Manrope',sans-serif; font-size:clamp(2.15rem,3.6vw,3.65rem); font-weight:800; letter-spacing:-.065em; line-height:.98; margin-bottom:18px; text-transform:uppercase; }
        .section-title .accent { color:var(--green); }
        .intro-copy p { color:var(--muted); font-size:.98rem; line-height:1.75; max-width:565px; }
        .mini-values { display:grid; gap:16px; grid-template-columns:1fr 1fr; margin-top:29px; }
        .mini-value { border-top:2px solid var(--green); padding-top:12px; }
        .mini-value strong { display:block; font-family:'Manrope',sans-serif; font-size:1.05rem; letter-spacing:-.04em; margin-bottom:3px; }
        .mini-value span { color:var(--muted); font-size:.77rem; line-height:1.45; }
        .classroom { background:var(--green); border-radius:18px; box-shadow:17px 17px 0 #d8e5dc; height:375px; overflow:hidden; position:relative; }
        .classroom::before { background:linear-gradient(90deg,rgba(255,255,255,.1) 1px,transparent 1px),linear-gradient(rgba(255,255,255,.1) 1px,transparent 1px); background-size:24px 24px; content:''; inset:0; opacity:.7; position:absolute; }
        .classroom-window { background:#bee9e7; border:7px solid #f7e557; border-radius:6px; height:176px; position:absolute; right:30px; top:30px; width:176px; }
        .classroom-window::before,.classroom-window::after { background:#f7e557; content:''; position:absolute; }
        .classroom-window::before { height:7px; left:0; top:78px; width:100%; }.classroom-window::after { height:100%; left:78px; top:0; width:7px; }
        .board { background:#0a4f43; border:7px solid #f0d57a; bottom:33px; height:146px; left:31px; position:absolute; transform:rotate(-3deg); width:68%; }
        .board::before { border:2px solid #c8ece0; border-radius:50%; content:''; height:63px; left:24px; position:absolute; top:32px; width:100px; }.board::after { background:repeating-linear-gradient(#c8ece0 0 3px,transparent 3px 19px); height:72px; position:absolute; right:24px; top:34px; width:82px; }
        .classroom-kid { bottom:20px; position:absolute; right:31px; z-index:3; }.classroom-kid .head { background:#875438; border-radius:50%; height:70px; left:21px; position:absolute; top:0; width:70px; }.classroom-kid .hair { background:#241b17; border-radius:55% 55% 25% 25%; height:37px; left:15px; position:absolute; top:-9px; width:82px; }.classroom-kid .shirt { background:var(--yellow); border-radius:48px 48px 12px 12px; height:118px; left:0; position:absolute; top:57px; width:112px; }.classroom-kid .book { background:#fff; border:3px solid #164d45; height:48px; left:-25px; position:absolute; top:107px; transform:rotate(15deg); width:72px; }
        .why { background:#10231f; color:#fff; padding:98px 0 104px; }
        .why-head { align-items:end; display:flex; justify-content:space-between; margin-bottom:35px; }
        .why .section-label { color:var(--yellow); }.why .section-title { margin-bottom:0; max-width:610px; }
        .why-note { color:#afc5bd; font-size:.87rem; line-height:1.6; max-width:270px; }
        .reason-grid { display:grid; gap:15px; grid-template-columns:repeat(4,1fr); }
        .reason-card { background:#1a3430; border-radius:12px; min-height:255px; overflow:hidden; padding:16px; position:relative; }
        .reason-picture { background:var(--mint); border-radius:8px; height:155px; margin-bottom:16px; overflow:hidden; position:relative; }
        .reason-picture::after { border:4px solid rgba(12,114,97,.34); border-radius:50%; content:''; height:120px; position:absolute; right:-24px; top:22px; width:120px; }
        .reason-picture.b { background:#e7d98c; }.reason-picture.c { background:#e8b9a3; }.reason-picture.d { background:#b3d8e5; }
        .reason-picture svg { bottom:14px; color:var(--green); height:112px; left:18px; position:absolute; width:112px; z-index:1; }
        .reason-card small { color:var(--yellow); font-size:.61rem; font-weight:800; letter-spacing:.1em; text-transform:uppercase; }.reason-card h3 { font-family:'Manrope',sans-serif; font-size:1.02rem; letter-spacing:-.04em; margin:5px 0 0; text-transform:uppercase; }
        .contact-links { padding:102px 0 68px; }
        .links-heading { max-width:500px; }.links-heading .section-title { margin-bottom:0; }
        .quick-grid { display:grid; gap:14px; grid-template-columns:repeat(4,1fr); margin-top:37px; }
        .quick-card { background:#fff; border:1px solid #e3e5df; border-radius:13px; box-shadow:0 7px 20px rgba(10,50,43,.06); min-height:188px; padding:20px; transition:transform .2s,box-shadow .2s; }
        .quick-card:hover { box-shadow:0 15px 26px rgba(10,50,43,.11); transform:translateY(-5px); }.quick-card.featured { background:var(--green); color:#fff; }
        .quick-icon { align-items:center; background:#dff2e9; border-radius:9px; color:var(--green); display:flex; height:36px; justify-content:center; margin-bottom:25px; width:36px; }.featured .quick-icon { background:var(--yellow); color:var(--green-deep); }.quick-icon svg { height:19px; width:19px; }
        .quick-card h3 { font-family:'Manrope',sans-serif; font-size:.94rem; letter-spacing:-.04em; margin-bottom:7px; text-transform:uppercase; }.quick-card p { color:var(--muted); font-size:.75rem; line-height:1.55; margin-bottom:15px; }.quick-card.featured p { color:#c8e2d8; }
        .quick-card a { color:var(--green); font-size:.68rem; font-weight:800; text-transform:uppercase; }.quick-card.featured a { color:var(--yellow); }
        .ribbon { background:var(--yellow); color:var(--green-deep); display:flex; font-family:'Manrope',sans-serif; font-size:.78rem; font-weight:800; gap:43px; letter-spacing:.025em; margin:18px 0 0; overflow:hidden; padding:17px 0; text-transform:uppercase; transform:rotate(-1.65deg) scale(1.03); white-space:nowrap; }
        .ribbon span { align-items:center; display:inline-flex; gap:43px; }.ribbon i { background:var(--green); border-radius:50%; display:inline-block; height:7px; width:7px; }
        .program-section { padding:105px 0; }.program-intro { align-items:end; display:flex; justify-content:space-between; margin-bottom:38px; }.program-intro .section-title { margin-bottom:0; max-width:650px; }.program-intro p { color:var(--muted); font-size:.86rem; line-height:1.65; margin:0; max-width:300px; }
        .stage-tabs { border-bottom:1px solid #cdd8d2; display:flex; gap:0; margin-bottom:33px; }.stage-tabs span { color:#71807b; flex:1; font-size:.68rem; font-weight:800; padding:0 0 14px; position:relative; text-align:center; text-transform:uppercase; }.stage-tabs span.active { color:var(--green); }.stage-tabs span.active::after { background:var(--green); bottom:-2px; content:''; height:4px; left:23%; position:absolute; width:54%; }
        .program-spotlight { align-items:center; display:grid; gap:52px; grid-template-columns:1fr .94fr; }.program-gallery { display:grid; gap:12px; grid-template-columns:1.35fr 1fr; height:296px; }.program-scene { background:#efd977; border-radius:13px; overflow:hidden; position:relative; }.program-scene::before { background:var(--green); border-radius:22px 22px 0 0; bottom:0; content:''; height:55%; left:18%; position:absolute; width:56%; }.program-scene::after { background:#fff; border:5px solid #d9bd57; border-radius:50%; content:''; height:105px; position:absolute; right:10%; top:12%; width:105px; }.gallery-small { display:grid; gap:12px; grid-template-rows:1fr 1fr; }.gallery-small div { border-radius:13px; overflow:hidden; position:relative; }.gallery-small div:first-child { background:#bbdcd4; }.gallery-small div:last-child { background:#f0ad8d; }.gallery-small div::before { background:var(--green); border-radius:50% 50% 8px 8px; bottom:-22px; content:''; height:110px; left:28%; position:absolute; width:73px; }.gallery-small div::after { background:#74472e; border-radius:50%; content:''; height:56px; left:35%; position:absolute; top:22%; width:56px; }
        .program-copy h3 { font-family:'Manrope',sans-serif; font-size:clamp(1.7rem,3vw,2.8rem); letter-spacing:-.065em; line-height:1; margin-bottom:15px; text-transform:uppercase; }.program-copy p { color:var(--muted); font-size:.88rem; line-height:1.72; }.program-copy .pill { margin-top:15px; }
        .calendar-section { background:#e8eee9; padding:96px 0 103px; }.calendar-card { background:#fff; border-radius:19px; box-shadow:0 17px 38px rgba(4,59,51,.12); display:grid; grid-template-columns:150px 1fr 240px; margin-top:40px; min-height:295px; overflow:hidden; }.calendar-months { background:var(--green); color:#dcefe8; display:flex; flex-direction:column; gap:9px; padding:22px; }.calendar-months strong { color:#fff; font-family:'Manrope',sans-serif; font-size:1rem; margin-bottom:3px; }.calendar-months span { font-size:.67rem; }.calendar-months span.active { background:var(--yellow); border-radius:5px; color:var(--green-deep); font-weight:800; margin:0 -7px; padding:5px 7px; }.calendar-main { padding:26px 30px; }.calendar-main h3 { font-family:'Manrope',sans-serif; font-size:1.2rem; letter-spacing:-.05em; margin-bottom:24px; text-transform:uppercase; }.weekdays,.calendar-days { display:grid; grid-template-columns:repeat(7,1fr); text-align:center; }.weekdays { color:#8a9691; font-size:.62rem; font-weight:800; margin-bottom:13px; }.calendar-days { gap:10px 4px; }.calendar-days span { align-items:center; border-radius:50%; display:flex; font-size:.7rem; height:27px; justify-content:center; margin:auto; width:27px; }.calendar-days span.event { background:var(--yellow); color:var(--green-deep); font-weight:800; }.calendar-days span.today { background:var(--green); color:#fff; font-weight:800; }.calendar-side { background:#fafcfb; border-left:1px solid #e5e9e6; padding:27px 22px; }.calendar-side h3 { color:var(--green); font-family:'Manrope',sans-serif; font-size:.91rem; letter-spacing:-.04em; margin-bottom:18px; text-transform:uppercase; }.event-row { align-items:flex-start; display:flex; gap:10px; margin:0 0 16px; }.event-row i { background:var(--coral); border-radius:50%; display:block; flex:0 0 auto; height:8px; margin-top:4px; width:8px; }.event-row:nth-of-type(3) i { background:var(--yellow); }.event-row:nth-of-type(4) i { background:var(--green); }.event-row b { display:block; font-size:.68rem; margin-bottom:2px; }.event-row span { color:var(--muted); font-size:.65rem; }
        .portal-cta { padding:106px 0; }.portal-box { background:var(--green-deep); border-radius:22px; color:#fff; display:grid; gap:25px; grid-template-columns:1fr .88fr; min-height:305px; overflow:hidden; position:relative; }.portal-box::after { border:1px solid rgba(248,235,47,.42); border-radius:50%; content:''; height:330px; position:absolute; right:-100px; top:-145px; width:330px; }.portal-copy { padding:54px 0 54px 57px; position:relative; z-index:1; }.portal-copy .section-label { color:var(--yellow); }.portal-copy .section-title { max-width:480px; }.portal-copy p { color:#bed4cc; line-height:1.65; max-width:475px; }.portal-art { align-self:end; height:100%; min-height:290px; position:relative; z-index:1; }.portal-device { background:#fff; border:8px solid #142d28; border-radius:20px 20px 0 0; bottom:0; box-shadow:10px 0 0 rgba(248,235,47,.95); height:215px; position:absolute; right:16%; transform:rotate(-5deg); width:270px; }.device-top { background:var(--green); border-radius:10px 10px 0 0; color:#fff; display:flex; font-size:.6rem; font-weight:800; justify-content:space-between; padding:12px; }.device-body { display:grid; gap:9px; grid-template-columns:75px 1fr; padding:12px; }.device-profile { background:#d9f0e6; border-radius:9px; min-height:145px; padding:11px; }.device-profile i { background:var(--yellow); border-radius:50%; display:block; height:40px; margin-bottom:11px; width:40px; }.device-profile span { background:#85bdad; border-radius:4px; display:block; height:6px; margin:6px 0; }.device-panels { display:grid; gap:9px; grid-template-rows:1fr 1fr; }.device-panels i { background:#f7ecc3; border-radius:8px; display:block; }.device-panels i:last-child { background:#dceae4; }
        .contact-section { background:#e8eee9; padding:94px 0; }.contact-layout { display:grid; gap:62px; grid-template-columns:.86fr 1.14fr; }.contact-copy .section-title { max-width:410px; }.contact-copy p { color:var(--muted); line-height:1.7; max-width:400px; }.contact-details { display:grid; gap:15px; margin-top:30px; }.contact-detail { align-items:center; display:flex; gap:12px; }.contact-detail i { align-items:center; background:var(--green); border-radius:50%; color:var(--yellow); display:flex; height:34px; justify-content:center; width:34px; }.contact-detail svg { height:16px; width:16px; }.contact-detail div { color:var(--muted); font-size:.75rem; }.contact-detail b { color:var(--ink); display:block; font-size:.81rem; margin-bottom:2px; }
        .contact-form { background:#fff; border-radius:17px; box-shadow:0 12px 30px rgba(9,50,42,.07); padding:33px; }.contact-form h3 { font-family:'Manrope',sans-serif; font-size:1.35rem; letter-spacing:-.05em; margin-bottom:23px; text-transform:uppercase; }.form-row { display:grid; gap:14px; grid-template-columns:1fr 1fr; }.field { margin-bottom:16px; }.field label { color:#3e5550; display:block; font-size:.7rem; font-weight:800; margin-bottom:7px; text-transform:uppercase; }.field input,.field textarea { background:#fbfcfb; border:1px solid #dbe2de; border-radius:7px; color:var(--ink); outline:none; padding:11px 12px; transition:border-color .2s,box-shadow .2s; width:100%; }.field textarea { min-height:92px; resize:vertical; }.field input:focus,.field textarea:focus { border-color:var(--green); box-shadow:0 0 0 3px rgba(12,114,97,.12); }.form-error { color:#c23b2b; display:block; font-size:.7rem; margin-top:5px; }.form-success { background:#e8f5ef; border:1px solid #aed7c4; border-radius:7px; color:var(--green-dark); font-size:.8rem; font-weight:700; margin-bottom:18px; padding:10px 12px; }
        .site-footer { background:#0a211c; color:#e2eee9; padding:60px 0 24px; }.footer-grid { display:grid; gap:35px; grid-template-columns:1.6fr .8fr .8fr .9fr; }.footer-brand .brand { color:#fff; margin-bottom:15px; }.footer-brand .brand-mark { background:#fff; }.footer-brand p { color:#a8c1b8; font-size:.8rem; line-height:1.7; max-width:270px; }.footer-col h3 { color:var(--yellow); font-size:.69rem; letter-spacing:.1em; margin:9px 0 16px; text-transform:uppercase; }.footer-col a,.footer-col span { color:#b6ccc4; display:block; font-size:.77rem; margin:0 0 11px; }.footer-col a:hover { color:#fff; }.footer-bottom { border-top:1px solid rgba(255,255,255,.13); color:#8aa79c; display:flex; font-size:.67rem; justify-content:space-between; margin-top:42px; padding-top:20px; }.footer-bottom div { display:flex; gap:18px; }.footer-bottom a:hover { color:#fff; }
        [data-reveal] { opacity:1; transform:none; }.has-js [data-reveal] { opacity:0; transform:translateY(18px); transition:opacity .6s ease,transform .6s ease; }.has-js [data-reveal].is-visible { opacity:1; transform:translateY(0); }.has-js [data-reveal="delay"] { transition-delay:.12s; }.has-js [data-reveal="delay-2"] { transition-delay:.2s; }
        @media (max-width:980px) { .nav-links { gap:15px; }.hero-grid { grid-template-columns:.95fr 1.05fr; }.reason-grid,.quick-grid { grid-template-columns:repeat(2,1fr); }.calendar-card { grid-template-columns:120px 1fr; }.calendar-side { border-left:0; border-top:1px solid #e5e9e6; grid-column:1/-1; }.calendar-side .event-list { display:grid; gap:8px; grid-template-columns:repeat(3,1fr); }.event-row { margin:0; }.split-intro,.program-spotlight,.contact-layout { gap:38px; }.footer-grid { grid-template-columns:1.3fr 1fr 1fr; }.footer-brand { grid-column:1/-1; } }
        @media (max-width:760px) { .page-width { padding-left:20px; padding-right:20px; }.nav-shell { height:68px; }.brand { font-size:.9rem; min-width:0; }.brand-mark { height:42px; width:42px; }.brand-mark img { height:36px; width:36px; }.nav-toggle { display:grid; place-items:center; }.nav-links { background:var(--paper); border-bottom:1px solid var(--line); box-shadow:0 12px 18px rgba(9,50,42,.08); display:none; left:0; padding:12px 20px 17px; position:absolute; right:0; top:68px; }.nav-links.is-open { display:grid; gap:3px; }.nav-links a { padding:10px 0; }.nav-actions .login-link { display:none; }.nav-actions .pill { min-height:38px; padding:0 13px; }.hero { padding-top:8px; }.hero-frame { border-radius:0 0 20px 20px; }.hero-grid { display:block; min-height:auto; }.hero-copy { padding:65px 0 42px; }.hero h1 { font-size:clamp(2.8rem,13vw,4rem); }.hero-visual { min-height:385px; }.hero-sun { height:220px; right:20px; top:45px; width:220px; }.school-scene { height:347px; }.school-scene .building { height:205px; }.school-scene .tower { height:250px; }.hero-stamp { bottom:20px; right:35%; transform:scale(.8) rotate(10deg); }.split-intro,.program-spotlight,.contact-layout,.portal-box { grid-template-columns:1fr; }.intro { padding:77px 0; }.classroom { height:320px; margin:0 10px 12px 0; }.why,.contact-links,.calendar-section,.portal-cta,.contact-section { padding:75px 0; }.why-head,.program-intro { align-items:start; display:block; }.why-note,.program-intro p { margin-top:16px; }.program-intro p { max-width:450px; }.reason-grid { grid-template-columns:1fr 1fr; }.reason-card { min-height:225px; padding:12px; }.reason-picture { height:128px; }.quick-grid { grid-template-columns:1fr 1fr; }.quick-card { min-height:170px; padding:16px; }.quick-icon { margin-bottom:18px; }.ribbon { font-size:.67rem; }.stage-tabs { overflow-x:auto; }.stage-tabs span { flex:0 0 145px; }.program-gallery { height:245px; }.calendar-card { display:block; }.calendar-months { flex-direction:row; flex-wrap:wrap; padding:17px; }.calendar-months strong { flex-basis:100%; }.calendar-months span.active { margin:0; }.calendar-main { padding:25px 17px; }.calendar-side .event-list { display:block; }.event-row { margin-bottom:13px; }.portal-copy { padding:44px 28px 12px; }.portal-art { min-height:230px; }.portal-device { height:190px; right:19%; width:240px; }.form-row { grid-template-columns:1fr; gap:0; }.contact-form { padding:23px; }.footer-grid { grid-template-columns:1fr 1fr; }.footer-brand { grid-column:1/-1; }.footer-bottom { align-items:flex-start; flex-direction:column; gap:13px; } }
        @media (max-width:390px) { .nav-actions .pill { display:none; }.reason-grid,.quick-grid { grid-template-columns:1fr; }.reason-card { min-height:230px; }.hero-buttons .pill { width:100%; }.mini-values { grid-template-columns:1fr; }.footer-grid { grid-template-columns:1fr; } }
    </style>
</head>
<body class="landing-page">
    <a class="skip-link" href="#main-content">Skip to content</a>
    <svg aria-hidden="true" style="height:0;position:absolute;width:0">
        <symbol id="icon-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M5 12h13M13 6l6 6-6 6"/></symbol>
        <symbol id="icon-menu" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h16M4 12h16M4 17h16"/></symbol>
        <symbol id="icon-check" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></symbol>
        <symbol id="icon-chat" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 15a4 4 0 0 1-4 4H8l-4 3V7a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4z"/><path d="M8 10h8M8 14h5"/></symbol>
        <symbol id="icon-card" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h3"/></symbol>
        <symbol id="icon-user" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-4 3.4-6 8-6s7.2 2 8 6"/></symbol>
        <symbol id="icon-file" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><path d="M14 3v6h6M8 14h8M8 18h5"/></symbol>
        <symbol id="icon-school" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m3 10 9-6 9 6v9H3z"/><path d="M8 20v-6h8v6M3 10h18M12 4v16"/></symbol>
        <symbol id="icon-globe" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></symbol>
        <symbol id="icon-book" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H12v18H7.5A3.5 3.5 0 0 0 4 23zM20 5.5A3.5 3.5 0 0 0 16.5 2H12v18h4.5A3.5 3.5 0 0 1 20 23z"/></symbol>
        <symbol id="icon-phone" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 3h3l2 5-2 1.5a15 15 0 0 0 6.5 6.5L16 14l5 2v3c0 1.1-.9 2-2 2C10.2 21 3 13.8 3 5c0-1.1.9-2 2-2z"/></symbol>
        <symbol id="icon-mail" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></symbol>
    </svg>

    <header class="site-header">
        <div class="page-width nav-shell">
            <a class="brand" href="{{ route('home') }}" aria-label="Summit Online School home"><span class="brand-mark"><img src="{{ asset('images/logo.png') }}" alt=""></span><span>Summit<br><span>Online School</span></span></a>
            <nav class="nav-links" data-site-navigation aria-label="Main navigation">
                <a href="#about">About</a><a href="#programs">Academics</a><a href="#why-summit">Why Summit</a><a href="#calendar">Calendar</a><a href="#contact">Contact</a>
            </nav>
            <div class="nav-actions"><a class="login-link" href="{{ route('login') }}">Portal login</a><a class="pill pill-primary" href="#contact">Enquire now</a><button class="nav-toggle" type="button" data-nav-toggle aria-label="Toggle navigation" aria-expanded="false"><svg><use href="#icon-menu"/></svg></button></div>
        </div>
    </header>

    <main id="main-content">
        <section class="hero">
            <div class="page-width"><div class="hero-frame"><div class="page-width hero-grid">
                <div class="hero-copy" data-reveal><div class="overline">A clear path to growth</div><h1>Learn with <strong>confidence.</strong></h1><p>Summit Online School brings inspiring teaching, supportive guidance, and one connected learning space to every student.</p><div class="hero-buttons"><a class="pill pill-yellow" href="#contact">Start learning <svg><use href="#icon-arrow"/></svg></a><a class="pill pill-outline" href="#about">Discover Summit</a></div><div class="hero-note"><i><svg style="height:14px;width:14px"><use href="#icon-check"/></svg></i>Admissions enquiries are open for the new term.</div></div>
                <div class="hero-visual" aria-label="Illustration of Summit students arriving at school"><div class="hero-sun"></div><div class="hero-pattern"></div><div class="school-scene"><div class="roof"></div><div class="tower"></div><div class="building"></div><div class="ground"></div><div class="student student-one"><i class="leg one"></i><i class="leg two"></i><i class="body"></i><i class="head"></i><i class="hair"></i><i class="bag"></i></div><div class="student student-two"><i class="leg one"></i><i class="leg two"></i><i class="body"></i><i class="head"></i><i class="hair"></i><i class="bag"></i></div><div class="student student-three"><i class="leg one"></i><i class="leg two"></i><i class="body"></i><i class="head"></i><i class="hair"></i><i class="bag"></i></div></div><div class="hero-stamp"><b>01</b>WE GROW<br>TOGETHER</div></div>
            </div></div></div>
        </section>

        <section class="intro" id="about"><div class="page-width split-intro"><div class="intro-copy" data-reveal><div class="section-label">Welcome to Summit</div><h2 class="section-title">A school that sees <span class="accent">every learner.</span></h2><p>We pair excellent teaching with genuine care. Every child has room to ask questions, discover what they love, and build the knowledge and character to thrive—at school and beyond.</p><div class="mini-values"><div class="mini-value"><strong>Personal attention</strong><span>Guidance that meets each student where they are.</span></div><div class="mini-value"><strong>Connected families</strong><span>Useful updates that make every week clearer.</span></div></div></div><div class="classroom" data-reveal="delay" aria-label="An illustrated classroom"><div class="classroom-window"></div><div class="board"></div><div class="classroom-kid"><i class="shirt"></i><i class="head"></i><i class="hair"></i><i class="book"></i></div></div></div></section>

        <section class="why" id="why-summit"><div class="page-width"><div class="why-head" data-reveal><div><div class="section-label">Why Summit?</div><h2 class="section-title">A better way to<br>build bright futures.</h2></div><p class="why-note">Strong foundations, wide horizons, and a learning experience that feels personal from day one.</p></div><div class="reason-grid"><article class="reason-card" data-reveal><div class="reason-picture"><svg><use href="#icon-school"/></svg></div><small>01 / Learning</small><h3>Strong foundations</h3></article><article class="reason-card" data-reveal="delay"><div class="reason-picture b"><svg><use href="#icon-globe"/></svg></div><small>02 / World ready</small><h3>Broad perspectives</h3></article><article class="reason-card" data-reveal="delay-2"><div class="reason-picture c"><svg><use href="#icon-user"/></svg></div><small>03 / Support</small><h3>Known and supported</h3></article><article class="reason-card" data-reveal><div class="reason-picture d"><svg><use href="#icon-book"/></svg></div><small>04 / Growth</small><h3>Learning for life</h3></article></div></div></section>

        <section class="contact-links"><div class="page-width"><div class="links-heading" data-reveal><div class="section-label">Contact us</div><h2 class="section-title">A quick link to <span class="accent">connect.</span></h2></div><div class="quick-grid"><article class="quick-card" data-reveal><div class="quick-icon"><svg><use href="#icon-chat"/></svg></div><h3>Registration enquiry</h3><p>Ask a question or start an admissions conversation with our team.</p><a href="#contact">Enquire now →</a></article><article class="quick-card featured" data-reveal="delay"><div class="quick-icon"><svg><use href="#icon-card"/></svg></div><h3>Family portal</h3><p>Access your child’s progress, weekly plan, and school updates.</p><a href="{{ route('login') }}">Portal login →</a></article><article class="quick-card" data-reveal="delay-2"><div class="quick-icon"><svg><use href="#icon-user"/></svg></div><h3>Parent support</h3><p>Find guidance and the right person for your family’s question.</p><a href="#contact">Get support →</a></article><article class="quick-card" data-reveal><div class="quick-icon"><svg><use href="#icon-file"/></svg></div><h3>School information</h3><p>Explore our learning approach, school routines, and programs.</p><a href="#programs">Explore more →</a></article></div></div></section>
        <div class="ribbon" aria-hidden="true"><span>Growing together <i></i> Learning with purpose <i></i> Building confidence <i></i> Growing together <i></i> Learning with purpose <i></i> Building confidence <i></i></span></div>

        <section class="program-section" id="programs"><div class="page-width"><div class="program-intro" data-reveal><div><div class="section-label">Our programs</div><h2 class="section-title">A journey of education <span class="accent">at Summit.</span></h2></div><p>We make each stage of learning feel purposeful, engaging, and suited to the child in front of us.</p></div><div class="stage-tabs" data-reveal="delay"><span class="active">Early years</span><span>Primary school</span><span>Middle school</span><span>Senior school</span></div><div class="program-spotlight"><div class="program-gallery" data-reveal><div class="program-scene"></div><div class="gallery-small"><div></div><div></div></div></div><div class="program-copy" data-reveal="delay"><div class="section-label">Early years</div><h3>Curiosity starts here.</h3><p>Our youngest learners explore through play, language, movement, and meaningful routines. It is a joyful first step that nurtures confidence and a lasting love of learning.</p><a class="pill pill-primary" href="#contact">Explore early years <svg><use href="#icon-arrow"/></svg></a></div></div></div></section>

        <section class="calendar-section" id="calendar"><div class="page-width"><div class="links-heading" data-reveal><div class="section-label">Plan ahead</div><h2 class="section-title">Academic <span class="accent">calendar.</span></h2></div><div class="calendar-card" data-reveal="delay"><div class="calendar-months"><strong>2026–27</strong><span>August</span><span class="active">September</span><span>October</span><span>November</span><span>December</span><span>January</span><span>February</span><span>March</span></div><div class="calendar-main"><h3>September 2026</h3><div class="weekdays"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendar-days"><span></span><span></span><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><span class="event">10</span><span>11</span><span>12</span><span>13</span><span>14</span><span>15</span><span>16</span><span>17</span><span>18</span><span>19</span><span>20</span><span>21</span><span>22</span><span>23</span><span>24</span><span>25</span><span>26</span><span class="today">27</span><span>28</span><span>29</span><span>30</span></div></div><div class="calendar-side"><h3>This month</h3><div class="event-list"><div class="event-row"><i></i><div><b>First day of school</b><span>10 September</span></div></div><div class="event-row"><i></i><div><b>Parent welcome session</b><span>15 September</span></div></div><div class="event-row"><i></i><div><b>Weekly reports available</b><span>27 September</span></div></div></div></div></div></div></section>

        <section class="portal-cta"><div class="page-width"><div class="portal-box"><div class="portal-copy" data-reveal><div class="section-label">One connected school</div><h2 class="section-title">The school day, <span style="color:var(--yellow)">within reach.</span></h2><p>Our family portal brings schedules, progress, weekly reports, and useful school updates into one simple space.</p><a class="pill pill-yellow" href="{{ route('login') }}">Visit the portal <svg><use href="#icon-arrow"/></svg></a></div><div class="portal-art" data-reveal="delay" aria-label="Preview of the family portal"><div class="portal-device"><div class="device-top"><span>My Summit</span><span>● ● ●</span></div><div class="device-body"><div class="device-profile"><i></i><span></span><span></span><span></span></div><div class="device-panels"><i></i><i></i></div></div></div></div></div></div></section>

        <section class="contact-section" id="contact"><div class="page-width contact-layout"><div class="contact-copy" data-reveal><div class="section-label">Start a conversation</div><h2 class="section-title">Let’s find the right next step.</h2><p>Tell us a little about your family and our admissions team will be happy to help you get to know Summit.</p><div class="contact-details"><div class="contact-detail"><i><svg><use href="#icon-phone"/></svg></i><div><b>Call our admissions team</b><a href="tel:+201000000000">+20 100 000 0000</a></div></div><div class="contact-detail"><i><svg><use href="#icon-mail"/></svg></i><div><b>Send us an email</b><a href="mailto:hello@summitacademy.edu">hello@summitacademy.edu</a></div></div></div></div><div class="contact-form" data-reveal="delay"><h3>Request information</h3>@if(session('contact_success'))<div class="form-success" role="status">{{ session('contact_success') }}</div>@endif<form action="{{ route('contact.store') }}" method="POST" novalidate>@csrf<div class="form-row"><div class="field"><label for="name">Your name</label><input id="name" name="name" type="text" value="{{ old('name') }}" autocomplete="name" required @error('name') aria-invalid="true" @enderror>@error('name')<span class="form-error">{{ $message }}</span>@enderror</div><div class="field"><label for="email">Email address</label><input id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="email" required @error('email') aria-invalid="true" @enderror>@error('email')<span class="form-error">{{ $message }}</span>@enderror</div></div><div class="field"><label for="phone">Phone number</label><input id="phone" name="phone" type="tel" value="{{ old('phone') }}" autocomplete="tel" required @error('phone') aria-invalid="true" @enderror>@error('phone')<span class="form-error">{{ $message }}</span>@enderror</div><div class="field"><label for="message">How can we help?</label><textarea id="message" name="message" required @error('message') aria-invalid="true" @enderror>{{ old('message') }}</textarea>@error('message')<span class="form-error">{{ $message }}</span>@enderror</div><button class="pill pill-primary" type="submit">Send enquiry <svg><use href="#icon-arrow"/></svg></button></form></div></div></section>
    </main>

    <footer class="site-footer"><div class="page-width"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="{{ route('home') }}"><span class="brand-mark"><img src="{{ asset('images/logo.png') }}" alt=""></span><span>Summit<br><span>Online School</span></span></a><p>Helping every learner build confidence, capability, and a bright future.</p></div><div class="footer-col"><h3>Explore</h3><a href="#about">About Summit</a><a href="#programs">Our programs</a><a href="#why-summit">Why Summit</a><a href="#calendar">Academic calendar</a></div><div class="footer-col"><h3>Families</h3><a href="#contact">Admissions</a><a href="#contact">Book a visit</a><a href="{{ route('login') }}">Family portal</a><a href="#contact">Contact us</a></div><div class="footer-col"><h3>Contact</h3><a href="tel:+201000000000">+20 100 000 0000</a><a href="mailto:hello@summitacademy.edu">hello@summitacademy.edu</a><span>Sunday–Thursday<br>8:00am–4:00pm</span></div></div><div class="footer-bottom"><span>© {{ date('Y') }} Summit Online School. All rights reserved.</span><div><a href="{{ route('privacy') }}">Privacy policy</a><a href="{{ route('terms') }}">Terms of use</a></div></div></div></footer>
</body>
</html>
